### ISSUE TITLE
Copy code from suhr fork

### ISSUE THREAD

**Issue by kpp** [zetok/tox#100]
Nice hack: https://github.com/suhr/tox/commit/64b92e2b2943a277266b9e83922be57de0297e5c

@suhr would you please update your code and create PR?

**Comment by suhr** [comment]
I'm currently working on other project, so I probably won't update this code.

Feel free to use it as you want though.

**Comment by kpp** [comment]
Ah, I liked your code...

Thank you. Anyway, its not an issue right now, I may wait for a ~month.

**Comment by kpp** [comment]
Fixed in https://github.com/tox-rs/tox/
