### ISSUE TITLE
TODO: replace Option<T> with Result<T> for packet parsing

### ISSUE THREAD

**Issue by zetok** [zetok/tox#41]
`Result<T>` allows for better error handling

Once there are proper error types, `Option<T>` will no longer be needed.
  

This issue is a part of https://github.com/zetok/tox/issues/107

**Comment by kpp** [comment]
It was done locally in tcp relay. See https://github.com/zetok/tox/blob/master/src/toxcore/tcp/binary_io.rs

All you need is to ^C^V code

**Comment by kpp** [comment]
Done in https://github.com/tox-rs/tox/
