### ISSUE TITLE
(Idea) Use `nom` instead of custom parsing code

### ISSUE THREAD

**Issue by zetok** [zetok/tox#42]
@kurnevsky how's the progress with it?

It's likely that there will be changes to the parsing code in the future, so it would be good to merge things that are ready before the changes.

**Comment by kurnevsky** [comment]
I haven't finished it yet, some parsers are not reimplemented. But it's not difficult to finish it I think. One thing that I didn't like about nom - you can't use custom error types without reimplementing dozen of parsers. You have to use u32 as custom error, plus default parsers might generate less detailed errors.

Opened PR: https://github.com/zetok/tox/pull/51

**Comment by kpp** [comment]
@zetok we may close it, right?
