### ISSUE TITLE
add DhtNode methods to support DhtRequest packets

### ISSUE THREAD

**Issue by zetok** [zetok/tox#84]
- [ ] `UdpCodec` implementation for `ToxCodec` needs to support more than just `DhtPacket`
  - consume/produce an enum for all UDP-based packets?
  - currently only `DhtRequest` aside from `DhtPacket` can be supported
- [ ] add method for handling DhtRequest
  - once handling method is done, include it in `DhtNode::handle_packet()` and expand its test

**Comment by kpp** [comment]
Done in https://github.com/tox-rs/tox/
