### ISSUE TITLE
Add DHT packet parsing

### ISSUE THREAD

**Issue by zetok** [zetok/tox#85]
Add parsing for packets (add types if don't exist already and implement `ToBytes` + `FromBytes` traits for them): 

- [x]  | `0x00`     | Ping Request
- [x]  | `0x01`     | Ping Response
- [x]  | `0x02`     | Nodes Request
- [x]  | `0x04`     | Nodes Response
- [ ]  | `0x18`     | Cookie Request
- [ ]  | `0x19`     | Cookie Response
- [ ]  | `0x1a`     | Crypto Handshake
- [ ]  | `0x1b`     | Crypto Data
- [ ]  | `0x20`     | DHT Request
- [ ]  | `0x21`     | LAN Discovery
- [ ]  | `0x80`     | Onion Request 0
- [ ]  | `0x81`     | Onion Request 1
- [ ]  | `0x82`     | Onion Request 2
- [ ]  | `0x83`     | Announce Request
- [ ]  | `0x84`     | Announce Response
- [ ]  | `0x85`     | Onion Data Request
- [ ]  | `0x86`     | Onion Data Response
- [ ]  | `0x8c`     | Onion Response 3
- [ ]  | `0x8d`     | Onion Response 2
- [ ]  | `0x8e`     | Onion Response 1
- [ ]  | `0xf0`     | Bootstrap Info

`DhtRequest` packets are partially supported, in order to support them fully Onion packets also need to have parsing implemented.

https://zetok.github.io/tox-spec/#packet-kind

**Comment by kpp** [comment]
Closed in favour of https://github.com/tox-rs/tox/
